FROM alpine:3

LABEL author = "Tio Hady Pranoto"
LABEL institution = "Kalimantan of Technology Institution" website = "itk.ac.id"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"